# Metadata for the site header and footer
title: Adam Pugh 2021
description: Vinyl Junction - Vintage Memories Cassettes LPs Books Record Storage

# Markdown parser and theme settings
markdown: kramdown
theme: minima
